export const unicornRules = {
  "unicorn/better-regex": "error",
  "unicorn/catch-error-name": "error",
  "unicorn/consistent-function-scoping": "error",
  "unicorn/custom-error-definition": "error",
  "unicorn/error-message": "error",
  "unicorn/escape-case": "error",
  "unicorn/expiring-todo-comments": "error",
  "unicorn/explicit-length-check": "error",
  "unicorn/filename-case": [
    "error",
    {
      case: "kebabCase",
      ignore: ["^CLAUDE\\.md$", "^README\\.md$", "^CHANGELOG\\.md$"],
    },
  ],
  "unicorn/new-for-builtins": "error",
  "unicorn/no-abusive-eslint-disable": "error",
  "unicorn/no-array-for-each": "error",
  "unicorn/no-array-push-push": "error",
  "unicorn/no-console-spaces": "error",
  "unicorn/no-for-loop": "error",
  "unicorn/no-lonely-if": "error",
  "unicorn/no-negated-condition": "error",
  "unicorn/no-nested-ternary": "error",
  "unicorn/no-null": "off",
  "unicorn/no-object-as-default-parameter": "error",
  "unicorn/no-process-exit": "error",
  "unicorn/no-unnecessary-await": "error",
  "unicorn/no-useless-length-check": "error",
  "unicorn/no-useless-spread": "error",
  "unicorn/no-useless-undefined": "error",
  "unicorn/number-literal-case": "error",
  "unicorn/prefer-add-event-listener": "error",
  "unicorn/prefer-array-find": "error",
  "unicorn/prefer-array-flat": "error",
  "unicorn/prefer-array-flat-map": "error",
  "unicorn/prefer-array-index-of": "error",
  "unicorn/prefer-array-some": "error",
  "unicorn/prefer-at": "error",
  "unicorn/prefer-code-point": "error",
  "unicorn/prefer-date-now": "error",
  "unicorn/prefer-default-parameters": "error",
  "unicorn/prefer-includes": "error",
  "unicorn/prefer-logical-operator-over-ternary": "error",
  "unicorn/prefer-modern-dom-apis": "error",
  "unicorn/prefer-modern-math-apis": "error",
  "unicorn/prefer-negative-index": "error",
  "unicorn/prefer-node-protocol": "error",
  "unicorn/prefer-number-properties": "error",
  "unicorn/prefer-optional-catch-binding": "error",
  "unicorn/prefer-prototype-methods": "error",
  "unicorn/prefer-query-selector": "error",
  "unicorn/prefer-set-has": "error",
  "unicorn/prefer-spread": "error",
  "unicorn/prefer-string-replace-all": "error",
  "unicorn/prefer-string-slice": "error",
  "unicorn/prefer-string-starts-ends-with": "error",
  "unicorn/prefer-string-trim-start-end": "error",
  "unicorn/prefer-switch": "error",
  "unicorn/prefer-ternary": "error",
  "unicorn/prefer-type-error": "error",
  "unicorn/prevent-abbreviations": "off",
  "unicorn/require-array-join-separator": "error",
  "unicorn/require-number-to-fixed-digits-argument": "error",
  "unicorn/throw-new-error": "error",
};

export const sonarjsRules = {
  "sonarjs/no-all-duplicated-branches": "error",
  "sonarjs/no-element-overwrite": "error",
  "sonarjs/no-empty-collection": "error",
  "sonarjs/no-extra-arguments": "error",
  "sonarjs/no-gratuitous-expressions": "error",
  "sonarjs/no-identical-conditions": "error",
  "sonarjs/no-identical-expressions": "error",
  "sonarjs/no-ignored-return": "error",
  "sonarjs/no-redundant-boolean": "error",
  "sonarjs/no-unused-collection": "error",
  "sonarjs/no-use-of-empty-return-value": "error",
  "sonarjs/no-useless-catch": "error",
  "sonarjs/prefer-immediate-return": "error",
  "sonarjs/prefer-object-literal": "error",
  "sonarjs/prefer-single-boolean-return": "error",
  "sonarjs/cognitive-complexity": ["warn", 15],
  "sonarjs/max-switch-cases": ["warn", 10],
  "sonarjs/no-collapsible-if": "warn",
  "sonarjs/no-duplicate-string": ["warn", { threshold: 3 }],
  "sonarjs/no-duplicated-branches": "warn",
  "sonarjs/no-identical-functions": "warn",
  "sonarjs/no-inverted-boolean-check": "warn",
  "sonarjs/no-nested-switch": "warn",
  "sonarjs/no-nested-template-literals": "warn",
  "sonarjs/no-redundant-jump": "warn",
  "sonarjs/no-small-switch": "warn",
  "sonarjs/prefer-while": "warn",
};

export const commonCodeQualityRules = {
  "no-console": "warn",
  "prefer-template": "error",
  "prefer-const": "error",
  "no-var": "error",
  "object-shorthand": "error",
  "no-useless-catch": "error",
  "no-param-reassign": "error",
  "no-void": "error",
  "no-return-assign": "error",
  "no-throw-literal": "error",
  "max-params": ["error", 4],
  "max-lines-per-function": ["warn", { max: 100, skipBlankLines: true, skipComments: true }],
  complexity: ["warn", 15],
  "no-restricted-imports": [
    "error",
    {
      patterns: ["../**/index"],
    },
  ],
  "linebreak-style": ["error", "unix"],
  semi: ["error", "always"],
  "no-extra-semi": "error",
  "default-case": 0,
  camelcase: 0,
  "no-async-promise-executor": "error",
  "no-await-in-loop": "error",
  "no-misleading-character-class": "error",
  "no-multi-assign": "error",
  "no-multi-str": "error",
  "no-nested-ternary": 0,
  "no-new": "error",
  "no-new-object": "error",
  "no-new-symbol": "error",
  "no-new-wrappers": "error",
  "no-obj-calls": "error",
  "no-path-concat": "error",
  "no-return-await": "error",
  "no-script-url": "error",
  "no-self-compare": "error",
  "no-sequences": "error",
  "no-shadow-restricted-names": "error",
  "no-sparse-arrays": "error",
  "no-tabs": "error",
  "no-template-curly-in-string": "error",
  "no-this-before-super": "error",
  "prefer-numeric-literals": "error",
  "prefer-object-spread": "error",
  "prefer-rest-params": "error",
  "prefer-spread": "error",
  "symbol-description": "error",
  "no-unreachable-loop": "error",
};
